Models/ErrorViewModel.cs
namespace WebApplication3.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Models/LOC_CityModel.cs
namespace WebApplication3.Models
{
	public class LOC_CityModel
	{
	}
}

Models/LOC_CountryModel.cs
namespace WebApplication3.Models
{
	public class LOC_CountryModel
	{
		public int CountryId { get; set; }		
		public string CountryName { get; set; } = string.Empty;	
		public string CountryCode { get; set; } = string.Empty;
	}
}

Models/LOC_StateModel.cs
namespace WebApplication3.Models
{
	public class LOC_StateModel
	{
	}
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Controllers/LOC_CityController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;

namespace WebApplication3.Controllers
{
	public class LOC_CityController : Controller
	{
        private readonly IConfiguration Configuration;
        public LOC_CityController(IConfiguration _configuration)
        {
            Configuration = _configuration;
        }

        public IActionResult LOC_City_List()
		{

            string str = this.Configuration.GetConnectionString("connectionString");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_City_SelectAll";
            SqlDataReader rdr = cmd.ExecuteReader();
            DataTable dt = new DataTable();
            dt.Load(rdr);
            conn.Close();

            return View(dt);
		}
		public IActionResult LOC_City_Add_Edit()
		{
			return View();
		}
		public IActionResult LOC_City_Update()
		{
			return View();
		}
	}
}

Controllers/LOC_CountryController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
	public class LOC_CountryController : Controller
	{
		private readonly IConfiguration Configuration;
		public LOC_CountryController(IConfiguration _configuration)
		{
			Configuration = _configuration;
		}

		public IActionResult LOC_Country_List()
		{
			string str = this.Configuration.GetConnectionString("connectionString");
			SqlConnection conn = new SqlConnection(str);
			conn.Open();	
			SqlCommand cmd = conn.CreateCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "PR_Country_SelectAll";
			SqlDataReader rdr = cmd.ExecuteReader();	
			DataTable dt = new DataTable();	
			dt.Load(rdr);	
			conn.Close();

			return View(dt);
		}
		public IActionResult LOC_Country_Add_Edit(LOC_CountryModel model)
		{
            DateTime dateTime = DateTime.Now;

            string str = this.Configuration.GetConnectionString("connectionString");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_Country_Insert";

			cmd.Parameters.AddWithValue("CountryID",model.CountryId);
            cmd.Parameters.AddWithValue("CountryName", model.CountryId);
			cmd.Parameters.AddWithValue("CountryCode", model.CountryId);
            cmd.Parameters.AddWithValue("Created", dateTime);
            cmd.Parameters.AddWithValue("Modified", dateTime);
			
			cmd.ExecuteNonQuery();
            conn.Close();

            return RedirectToAction("LOC_Country_List");		
		}
		public IActionResult LOC_Country_Update()
		{
			return View();
		}
    }
}

Controllers/LOC_StateController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;

namespace WebApplication3.Controllers
{
	public class LOC_StateController : Controller
	{

        private readonly IConfiguration Configuration;
        public LOC_StateController(IConfiguration _configuration)
        {
            Configuration = _configuration;
        }

        public IActionResult LOC_State_List()
		{

            string str = this.Configuration.GetConnectionString("connectionString");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_State_SelectAll";
            SqlDataReader rdr = cmd.ExecuteReader();
            DataTable dt = new DataTable();
            dt.Load(rdr);
            conn.Close();

            return View(dt);
		}
		public IActionResult LOC_State_Add_Edit()
		{
			return View();
		}
		public IActionResult LOC_State_Update()
		{
			return View();
		}
	}
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/LOC_City/LOC_City_Add_Edit.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<style>
		body {
			font-family: Arial, sans-serif;
			background-color: #f0f0f0;
			margin: 0;
			padding: 0;
			justify-content: center;
			align-items: center;
			min-height: 100vh;
		}

		.form-container {
			background-color: #fff;
			padding: 20px;
			border-radius: 8px;
			box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
			width: 300px;
			transform: translate(170%, 20%);
		}

		.form-group {
			margin-bottom: 15px;
		}

		label {
			display: block;
			margin-bottom: 5px;
			font-weight: bold;
		}

		input[type="text"] {
			width: 100%;
			padding: 8px;
			border: 1px solid #ccc;
			border-radius: 4px;
			font-size: 14px;
		}

		input[type="submit"] {
			background-color: #007bff;
			color: #fff;
			padding: 10px 15px;
			border: none;
			border-radius: 4px;
			cursor: pointer;
			font-size: 14px;
		}

			input[type="submit"]:hover {
				background-color: #0056b3;
			}
	</style>

	<title>Country Form</title>
</head>
<body>
	<div class="form-container">
		<form action="#" method="post">
			<div class="form-group">
				<label for="cityID">CityID:</label>
				<input type="text" id="cityID" name="cityID" required>
			</div>
			<div class="form-group">
				<label for="cityName">CityName:</label>
				<input type="text" id="cityName" name="cityName" required>
			</div>
			<div class="form-group">
				<label for="stateID">StateID:</label>
				<input type="text" id="stateID" name="stateID" required>
			</div>
			<div class="form-group">
				<label for="countryID">CountryID:</label>
				<input type="text" id="countryID" name="countryID" required>
			</div>
			<div class="form-group">
				<label for="cityCode">CityCode:</label>
				<input type="text" id="cityCode" name="cityCode" required>
			</div>
			<input type="submit" value="Submit">
		</form>
	</div>
</body>
</html>

Views/LOC_City/LOC_City_List.cshtml
@using System.Data;
@model DataTable;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Bootstrap Simple Data Table</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <style>

        body {
            color: #566787;
            background: #f5f5f5;
            font-family: 'Roboto', sans-serif;
        }

        .table-responsive {
            margin: 30px 0;
        }

        .table-wrapper {
            min-width: 1000px;
            background: #fff;
            padding: 20px;
            box-shadow: 0 1px 1px rgba(0,0,0,.05);
        }

        .table-title {
            padding-bottom: 10px;
            margin: 0 0 10px;
            min-width: 100%;
        }

            .table-title h2 {
                margin: 8px 0 0;
                font-size: 22px;
            }

        .search-box {
            position: relative;
            float: right;
        }

            .search-box input {
                height: 34px;
                border-radius: 20px;
                padding-left: 35px;
                border-color: #ddd;
                box-shadow: none;
            }

                .search-box input:focus {
                    border-color: #3FBAE4;
                }

            .search-box i {
                color: #a0a5b1;
                position: absolute;
                font-size: 19px;
                top: 8px;
                left: 10px;
            }

        table.table tr th, table.table tr td {
            border-color: #e9e9e9;
        }

        table.table-striped tbody tr:nth-of-type(odd) {
            background-color: #fcfcfc;
        }

        table.table-striped.table-hover tbody tr:hover {
            background: #f5f5f5;
        }

        table.table th i {
            font-size: 13px;
            margin: 0 5px;
            cursor: pointer;
        }

        table.table td:last-child {
            width: 130px;
        }

        table.table td a {
            color: #a0a5b1;
            display: inline-block;
            margin: 0 5px;
        }

            table.table td a.view {
                color: #03A9F4;
            }

            table.table td a.edit {
                color: #FFC107;
            }

            table.table td a.delete {
                color: #E34724;
            }

        table.table td i {
            font-size: 19px;
        }

        .pagination {
            float: right;
            margin: 0 0 5px;
        }

            .pagination li a {
                border: none;
                font-size: 95%;
                width: 30px;
                height: 30px;
                color: #999;
                margin: 0 2px;
                line-height: 30px;
                border-radius: 30px !important;
                text-align: center;
                padding: 0;
            }

                .pagination li a:hover {
                    color: #666;
                }

            .pagination li.active a {
                background: #03A9F4;
            }

                .pagination li.active a:hover {
                    background: #0397d6;
                }

            .pagination li.disabled i {
                color: #ccc;
            }

            .pagination li i {
                font-size: 16px;
                padding-top: 6px
            }

        .hint-text {
            float: left;
            margin-top: 6px;
            font-size: 95%;
        }
    </style>
    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
</head>
<body>

    <a class="nav-link text-dark" asp-area="" asp-controller="LOC_City" asp-action="LOC_City_Add_Edit">Add City</a>

    <div class="container-xl">
        <div class="table-responsive">
            <div class="table-wrapper">
                <div class="table-title">
                    <div class="row">
                        <div class="col-sm-8"><h2><b>City</b> Details</h2></div>
                        <div class="col-sm-4">
                            <div class="search-box">
                                <i class="material-icons">&#xE8B6;</i>
                                <input type="text" class="form-control" placeholder="Search&hellip;">
                            </div>
                        </div>
                    </div>
                </div>
                <table class="table table-striped table-hover table-bordered">
                    <thead>
                        <tr>
                            <th>Sr No.</th>
                            <th>CityID</th>
                            <th>CityName</th>
                            <th>StateID</th>
                            <th>CountryID</th>
                            <th>CityCode</th>
                            <th>Created</th>
                            <th>Modified</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>

                        @{
                            int a = 1;
                            foreach (DataRow dr in Model.Rows)
                            {
                                <tr>
                                    <td>@a</td>
                                    <td>@dr["CityID"]</td>
                                    <td>@dr["CityName"]</td>
                                    <td>@dr["StateID"]</td>
                                    <td>@dr["CountryID"]</td>
                                    <td>@dr["CityCode"]</td>
                                    <td>@Convert.ToDateTime(@dr["CreationDate"]).ToString("dd-MM-yyyy")</td>
                                    <td>@Convert.ToDateTime(@dr["Modified"]).ToString("dd-MM-yyyy")</td>
                                    <td>
                                        <a href="#" class="view" title="View" data-toggle="tooltip"><i class="material-icons">&#xE417;</i></a>
                                        <a asp-area="" asp-controller="LOC_Country" asp-action="LOC_Country_Update" class="edit" title="Edit" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
                                        <a href="#" class="delete" title="Delete" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
                                    </td>
                                </tr>
                                a++;
                            }

                        }


                    </tbody>
                </table>

            </div>
        </div>
    </div>

</body>
</html>

<!--

    <i class="fa fa-sort"></i>
    <i class="fa fa-sort"></i>
    <i class="fa fa-sort"></i>

    <div class="clearfix">
                <div class="hint-text">Showing <b>5</b> out of <b>25</b> entries</div>
                <ul class="pagination">
                    <li class="page-item disabled"><a href="#"><i class="fa fa-angle-double-left"></i></a></li>
                    <li class="page-item"><a href="#" class="page-link">1</a></li>
                    <li class="page-item"><a href="#" class="page-link">2</a></li>
                    <li class="page-item active"><a href="#" class="page-link">3</a></li>
                    <li class="page-item"><a href="#" class="page-link">4</a></li>
                    <li class="page-item"><a href="#" class="page-link">5</a></li>
                    <li class="page-item"><a href="#" class="page-link"><i class="fa fa-angle-double-right"></i></a></li>
                </ul>
            </div>





            <tr>
                            <td>1</td>
                            <td>Thomas Hardy</td>
                            <td>89 Chiaroscuro Rd.</td>
                            <td>Portland</td>
                            <td>97219</td>
                            <td>97219</td>
                            <td>97219</td>
                            <td>USA</td>
                            <td>
                                <a asp-area="" asp-controller="LOC_City" asp-action="LOC_City_Update"  class="edit" title="Edit" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
                                <a href="#" class="delete" title="Delete" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
                            </td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td>Maria Anders</td>
                            <td>Obere Str. 57</td>
                            <td>Berlin</td>
                            <td>12209</td>
                            <td>12209</td>
                            <td>12209</td>
                            <td>Germany</td>
                            <td>
                                <a asp-area="" asp-controller="LOC_City" asp-action="LOC_City_Update" class="edit" title="Edit" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
                                <a href="#" class="delete" title="Delete" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
                            </td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>Fran Wilson</td>
                            <td>C/ Araquil, 67</td>
                            <td>Madrid</td>
                            <td>28023</td>
                            <td>28023</td>
                            <td>28023</td>
                            <td>Spain</td>
                            <td>
                                <a asp-area="" asp-controller="LOC_City" asp-action="LOC_City_Update" class="edit" title="Edit" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
                                <a href="#" class="delete" title="Delete" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
                            </td>
                        </tr>
                        <tr>
                            <td>4</td>
                            <td>Dominique Perrier</td>
                            <td>25, rue Lauriston</td>
                            <td>Paris</td>
                            <td>75016</td>
                            <td>75016</td>
                            <td>75016</td>
                            <td>France</td>
                            <td>
                                <a asp-area="" asp-controller="LOC_City" asp-action="LOC_City_Update" class="edit" title="Edit" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
                                <a href="#" class="delete" title="Delete" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
                            </td>
                        </tr>
                        <tr>
                            <td>5</td>
                            <td>Martin Blank</td>
                            <td>Via Monte Bianco 34</td>
                            <td>Turin</td>
                            <td>10100</td>
                            <td>10100</td>
                            <td>10100</td>
                            <td>Italy</td>
                            <td>
                                <a asp-area="" asp-controller="LOC_City" asp-action="LOC_City_Update" class="edit" title="Edit" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
                                <a href="#" class="delete" title="Delete" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></a>
                            </td>
                        </tr>

-->

Views/LOC_City/LOC_City_Update.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<style>
		body {
			font-family: Arial, sans-serif;
			background-color: #f0f0f0;
			margin: 0;
			padding: 0;
			justify-content: center;
			align-items: center;
			min-height: 100vh;
		}

		.form-container {
			background-color: #fff;
			padding: 20px;
			border-radius: 8px;
			box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
			width: 300px;
			transform: translate(170%, 20%);
		}

		.form-group {
			margin-bottom: 15px;
		}

		label {
			display: block;
			margin-bottom: 5px;
			font-weight: bold;
		}

		input[type="text"] {
			width: 100%;
			padding: 8px;
			border: 1px solid #ccc;
			border-radius: 4px;
			font-size: 14px;
		}

		input[type="submit"] {
			background-color: #007bff;
			color: #fff;
			padding: 10px 15px;
			border: none;
			border-radius: 4px;
			cursor: pointer;
			font-size: 14px;
		}

			input[type="submit"]:hover {
				background-color: #0056b3;
			}
	</style>

	<title>Country Form</title>
</head>
<body>
	<div class="form-container">
		<form action="#" method="post">
			<div class="form-group">
				<label for="cityID">CityID:</label>
				<input type="text" id="cityID" name="cityID" required>
			</div>
			<div class="form-group">
				<label for="cityName">CityName:</label>
				<input type="text" id="cityName" name="cityName" required>
			</div>
			<div class="form-group">
				<label for="stateID">StateID:</label>
				<input type="text" id="stateID" name="stateID" required>
			</div>
			<div class="form-group">
				<label for="countryID">CountryID:</label>
				<input type="text" id="countryID" name="countryID" required>
			</div>
			<div class="form-group">
				<label for="cityCode">CityCode:</label>
				<input type="text" id="cityCode" name="cityCode" required>
			</div>
			<input type="submit" value="Update">
		</form>
	</div>
</body>
</html>

Views/LOC_Country/LOC_Country_Add_Edit.cshtml
@using System.Data;
@model LOC_CountryModel;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }

        .form-container {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
            width: 300px;
            transform: translate(170%, 20%);
        }

        .form-group {
            margin-bottom: 15px;
        }

        label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
        }

        input[type="text"] {
            width: 100%;
            padding: 8px;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 14px;
        }

        input[type="submit"] {
            background-color: #007bff;
            color: #fff;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 14px;
        }

            input[type="submit"]:hover {
                background-color: #0056b3;
            }
    </style>

    <title>Country Form</title>
</head>
<body>
    <div class="form-container">
        <form method="post" asp-controller="LOC_Country" asp-action="LOC_Country_Add_Edit">
            <div class="form-group">
                <label for="countryID">CountryID:</label>
                <input type="text" id="countryID" name="countryID" required>
            </div>
            <div class="form-group">
                <label for="countryName">CountryName:</label>
                <input type="text" id="countryName" name="countryName" required>
            </div>
            <div class="form-group">
                <label for="countryCode">CountryCode:</label>
                <input type="text" id="countryCode" name="countryCode" required>
            </div>
            <input type="submit" value="Submit">
        </form>
    </div>
</body>
</html>

<!--

    margin: 0;
    padding: 0;
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;

-->

Views/LOC_Country/LOC_Country_Update.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
        }

        .form-container {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
            width: 300px;
            transform: translate(170%, 20%);
        }

        .form-group {
            margin-bottom: 15px;
        }

        label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
        }

        input[type="text"] {
            width: 100%;
            padding: 8px;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 14px;
        }

        input[type="submit"] {
            background-color: #007bff;
            color: #fff;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 14px;
        }

            input[type="submit"]:hover {
                background-color: #0056b3;
            }
    </style>

    <title>Country Form</title>
</head>
<body>
    <div class="form-container">
        <form action="#" method="post">
            <div class="form-group">
                <label for="countryID">CountryID:</label>
                <input type="text" id="countryID" name="countryID" required>
            </div>
            <div class="form-group">
                <label for="countryName">CountryName:</label>
                <input type="text" id="countryName" name="countryName" required>
            </div>
            <div class="form-group">
                <label for="countryCode">CountryCode:</label>
                <input type="text" id="countryCode" name="countryCode" required>
            </div>
            <input type="submit" value="Update">
        </form>
    </div>
</body>
</html>

<!--

    margin: 0;
    padding: 0;
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;

-->

Views/LOC_State/LOC_State_Add_Edit.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<style>
		body {
			font-family: Arial, sans-serif;
			background-color: #f0f0f0;
			margin: 0;
			padding: 0;
			justify-content: center;
			align-items: center;
			min-height: 100vh;
		}

		.form-container {
			background-color: #fff;
			padding: 20px;
			border-radius: 8px;
			box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
			width: 300px;
			transform: translate(170%, 20%);
		}

		.form-group {
			margin-bottom: 15px;
		}

		label {
			display: block;
			margin-bottom: 5px;
			font-weight: bold;
		}

		input[type="text"] {
			width: 100%;
			padding: 8px;
			border: 1px solid #ccc;
			border-radius: 4px;
			font-size: 14px;
		}

		input[type="submit"] {
			background-color: #007bff;
			color: #fff;
			padding: 10px 15px;
			border: none;
			border-radius: 4px;
			cursor: pointer;
			font-size: 14px;
		}

			input[type="submit"]:hover {
				background-color: #0056b3;
			}
	</style>

	<title>Country Form</title>
</head>
<body>
	<div class="form-container">
		<form action="#" method="post">
			<div class="form-group">
				<label for="stateID">StateID:</label>
				<input type="text" id="stateID" name="stateID" required>
			</div>
			<div class="form-group">
				<label for="stateName">StateName:</label>
				<input type="text" id="stateName" name="stateName" required>
			</div>
			<div class="form-group">
				<label for="countryID">CountryID:</label>
				<input type="text" id="countryID" name="countryID" required>
			</div>
			<div class="form-group">
				<label for="stateCode">StateCode:</label>
				<input type="text" id="stateCode" name="stateCode" required>
			</div>
			<input type="submit" value="Submit">
		</form>
	</div>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LOC_Country" asp-action="LOC_Country_List">Country</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LOC_State" asp-action="LOC_State_List">State</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LOC_City" asp-action="LOC_City_List">City</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplication3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>